name: Daily DevSync Update

on:
  schedule:
    # Runs once per day at 00:00 UTC
    - cron: '53 19 * * *'
  workflow_dispatch: # Allows you to trigger it manually for testing

jobs:
  update-repo:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: DevSync Action for 23f2005169@ds.study.iitm.ac.in
        run: |
          date >> daily_log.txt
          git config --local user.email "23f2005169@ds.study.iitm.ac.in"
          git config --local user.name "DevSync Automation"
          git add daily_log.txt
          git commit -m "Automated daily update for DevSync [skip ci]"
          git push
